/** Maps sidebar routes to backend MenuCode values. */
export const ROUTE_MENU_CODES: Record<string, string> = {
  '/gym-admin/dashboard': 'DASHBOARD',
  '/gym-admin/analytics/revenue': 'REVENUE_ANALYTICS',
  '/gym-admin/analytics/members': 'MEMBER_ANALYTICS',
  '/gym-admin/analytics/attendance': 'ATTENDANCE_ANALYTICS',
  '/gym-admin/analytics/trainers': 'TRAINER_ANALYTICS',
  '/gym-admin/members': 'MEMBERS',
  '/gym-admin/leads': 'LEADS',
  '/gym-admin/expenses': 'EXPENSES',
  '/gym-admin/payroll': 'PAYROLL',
  '/gym-admin/financial': 'FINANCIAL',
  '/gym-admin/trainers': 'TRAINERS',
  '/gym-admin/membership-plans': 'MEMBERSHIP_PLANS',
  '/gym-admin/memberships': 'MEMBERSHIPS',
  '/gym-admin/payments': 'PAYMENTS',
  '/gym-admin/notifications': 'NOTIFICATIONS',
  '/gym-admin/revenue': 'REVENUE',
  '/gym-admin/attendance': 'ATTENDANCE',
  '/gym-admin/attendance/reports': 'ATTENDANCE_REPORTS',
  '/gym-admin/audit': 'AUDIT_LOGS',
  '/gym-admin/diet-plans': 'DIET_PLANS',
  '/gym-admin/workout-plans': 'WORKOUT_PLANS',
  '/gym-admin/subscription': 'SUBSCRIPTIONS',
  '/gym-admin/settings/branding': 'GYM_BRANDING',
  '/gym-admin/branches': 'BRANCHES',
  '/gym-admin/branches/dashboard': 'BRANCH_DASHBOARD',
  '/gym-admin/branches/analytics': 'BRANCH_ANALYTICS',
  '/gym-admin/branches/transfers': 'BRANCH_TRANSFERS',
  '/gym-admin/branches/targets': 'BRANCH_TARGETS',
  '/gym-admin/mobile-notifications': 'MOBILE_PUSH',
  '/gym-admin/mobile-analytics': 'MOBILE_ANALYTICS',
  '/gym-admin/ai': 'AI_DASHBOARD',
  '/gym-admin/ai/insights': 'AI_INSIGHTS',
  '/gym-admin/bookings': 'BOOKINGS',
  '/gym-admin/schedules': 'CLASS_SCHEDULES',
  '/gym-admin/booking-analytics': 'BOOKING_ANALYTICS',
  '/gym-admin/website-builder': 'WEBSITE_BUILDER',
  '/gym-admin/website-builder/analytics': 'WEBSITE_ANALYTICS',
  '/gym-admin/branding': 'WHITE_LABEL',
  '/gym-admin/white-label': 'WHITE_LABEL',
  '/trainer': 'DASHBOARD',
  '/trainer/members': 'MEMBERS',
  '/trainer/attendance': 'ATTENDANCE',
  '/trainer/workout-plans': 'WORKOUT_PLANS',
  '/trainer/ai-recommendations': 'AI_RECOMMENDATIONS',
  '/trainer/schedule': 'CLASS_SCHEDULES',
  '/trainer/bookings': 'BOOKINGS',
  '/member/dashboard': 'DASHBOARD',
  '/member/goals': 'MEMBERS',
  '/member/progress': 'MEMBERS',
  '/member/workouts': 'WORKOUT_PLANS',
  '/member/diets': 'DIET_PLANS',
  '/member/water': 'MEMBERS',
  '/member/referrals': 'MEMBERS',
  '/member/feedback': 'MEMBERS',
  '/member/profile': 'MEMBERS',
  '/member/diet': 'DIET_PLANS',
  '/member/workout': 'WORKOUT_PLANS',
  '/member/checkout': 'PAYMENTS',
  '/member/bookings': 'BOOKINGS',
};

export function resolveMenuCodeForRoute(route: string): string | undefined {
  if (ROUTE_MENU_CODES[route]) return ROUTE_MENU_CODES[route];
  const match = Object.keys(ROUTE_MENU_CODES)
    .filter((key) => route.startsWith(key + '/'))
    .sort((a, b) => b.length - a.length)[0];
  return match ? ROUTE_MENU_CODES[match] : undefined;
}
