export const env = {
  baseUrl: process.env.BASE_URL ?? 'http://localhost:4200',
  apiUrl: process.env.API_URL ?? 'http://localhost:5088',

  superAdmin: {
    loginIdentifier: process.env.SUPER_ADMIN_LOGIN_IDENTIFIER ?? 'superadmin',
    password: process.env.SUPER_ADMIN_PASSWORD ?? 'SuperAdmin@123',
  },

  gymAdmin: {
    loginIdentifier: process.env.GYM_ADMIN_LOGIN_IDENTIFIER ?? 'admin',
    password: process.env.GYM_ADMIN_PASSWORD ?? 'Demo@123',
    gymId: process.env.DEMO_GYM_ID ?? 'b2edbb38-ee01-4d17-94b6-1b3303807b91',
    gymName: process.env.DEMO_GYM_NAME ?? 'FitZone Demo Gym',
  },

  trainer: {
    loginIdentifier: process.env.TRAINER_LOGIN_IDENTIFIER ?? 'trainer1',
    password: process.env.TRAINER_PASSWORD ?? 'Demo@123',
    gymId: process.env.DEMO_GYM_ID ?? 'b2edbb38-ee01-4d17-94b6-1b3303807b91',
  },

  routes: {
    login: '/auth/login',
    superAdminHome: '/super-admin',
    tenantMenus: '/super-admin/tenant-menus',
    gymAdminDashboard: '/gym-admin/dashboard',
    members: '/gym-admin/members',
    trainers: '/gym-admin/trainers',
    leads: '/gym-admin/leads',
    leadsCreate: '/gym-admin/leads/create',
    membershipPlans: '/gym-admin/membership-plans',
    memberships: '/gym-admin/memberships',
    payments: '/gym-admin/payments',
    revenue: '/gym-admin/revenue',
    attendance: '/gym-admin/attendance',
    attendanceCheckIn: '/gym-admin/attendance/check-in',
    attendanceCheckOut: '/gym-admin/attendance/check-out',
    attendanceReports: '/gym-admin/attendance/reports',
    dietPlans: '/gym-admin/diet-plans',
    dietPlansNew: '/gym-admin/diet-plans/new',
    workoutPlans: '/gym-admin/workout-plans',
    workoutPlansNew: '/gym-admin/workout-plans/new',
    workoutExercises: '/gym-admin/workout-plans/exercises',
    notifications: '/gym-admin/notifications',
    notificationTemplates: '/gym-admin/notifications/templates',
    notificationHistory: '/gym-admin/notifications/history',
    notificationTest: '/gym-admin/notifications/test',
    analyticsRevenue: '/gym-admin/analytics/revenue',
    analyticsMembers: '/gym-admin/analytics/members',
    branches: '/gym-admin/branches',
    branchDashboard: '/gym-admin/branches/dashboard',
    whiteLabel: '/gym-admin/white-label',
    whiteLabelPreview: '/gym-admin/white-label/preview',
    websiteBuilder: '/gym-admin/website-builder',
    websitePages: '/gym-admin/website-builder/pages',
    trainerHome: '/trainer',
  },

  menuCodes: {
    members: 'MEMBERS',
    trainers: 'TRAINERS',
    leads: 'LEADS',
    memberships: 'MEMBERSHIPS',
    payments: 'PAYMENTS',
    attendance: 'ATTENDANCE',
    dietPlans: 'DIET_PLANS',
    workoutPlans: 'WORKOUT_PLANS',
    notifications: 'NOTIFICATIONS',
    branches: 'BRANCHES',
    whiteLabel: 'WHITE_LABEL',
    publicWebsite: 'WEBSITE_BUILDER',
  },
} as const;
